spring:
  application:
    name: rabbitMq-spring
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queueName: tms-alert
    exchange:
      name: tms
    routing:
      key:
        tms_routing_key